### ISSUE TITLE
AccessViolationException when using RequestEncryptedAppTicketAsync

### ISSUE THREAD

**Issue by fffe0d0a** [Facepunch/Facepunch.Steamworks#298]
When using Net Core 3 preview 7 and stepping into
```
SteamClient.Init(_appid_);
byte[] data = await SteamUser.RequestEncryptedAppTicketAsync(new byte[] { 1, 2, 3 });
```
the program will throw System.AccessViolationException when providing RequestEncryptedAppTicketAsync a byte[] as a parameter. If no parameter is provided, no exception is thrown, but the result will always be null. If I don't step into the method and just run the program with these two lines at the start, the Steam process on my computer will crash and the program will hang indefinitely.

When using Net Framework 4.7.2 or Net Core 2.1, no exception is thrown but the result of the method is always null. Am I doing something wrong, or is this an unintentional issue?

**Comment by fffe0d0a** [comment]
I should add that the stack looks like this
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Steamworks.ISteamUser+<RequestEncryptedAppTicket>d__68.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Steamworks.ISteamUser+<RequestEncryptedAppTicket>d__68, Facepunch.Steamworks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]](<RequestEncryptedAppTicket>d__68 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Nullable`1[[Steamworks.Data.EncryptedAppTicketResponse_t, Facepunch.Steamworks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Steamworks.ISteamUser+<RequestEncryptedAppTicket>d__68, Facepunch.Steamworks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]](<RequestEncryptedAppTicket>d__68 ByRef)
   at Steamworks.ISteamUser.RequestEncryptedAppTicket(IntPtr, Int32)
   at Steamworks.SteamUser+<RequestEncryptedAppTicketAsync>d__67.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Steamworks.SteamUser+<RequestEncryptedAppTicketAsync>d__67, Facepunch.Steamworks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]](<RequestEncryptedAppTicketAsync>d__67 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Steamworks.SteamUser+<RequestEncryptedAppTicketAsync>d__67, Facepunch.Steamworks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]](<RequestEncryptedAppTicketAsync>d__67 ByRef)
   at Steamworks.SteamUser.RequestEncryptedAppTicketAsync(Byte[])
   at Test_Client.Program+<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Test_Client.Program.Main(System.String[])
   at Test_Client.Program.<Main>(System.String[])
```

**Comment by darvell** [comment]
Might be just too much crap on the heap and .NET Core 3.0 is working against it.

Are you running your main function in a Task? The new Span<T> stuff might work out great for this.
