### ISSUE TITLE
Compatibilty standalone dotnet core linux application

### ISSUE THREAD

**Issue by fanmanpro** [Facepunch/Facepunch.Steamworks#470]
I've been trying to follow the instructions for installing a dedicated game server just using the server libary.

I have a simple dotnet console application looking like this:
```
using Steamworks;
using System;
namespace steamworksexample
{
    class Program
    {
        static void Main(string[] args)
        {
            var serverInit = new SteamServerInit()
            {
                GamePort = 28015,
                Secure = true,
                QueryPort = 28016
            };

            try
            {
                Steamworks.SteamServer.Init(1027120, serverInit, true);
                Console.WriteLine("I'm in");
            }
            catch (System.Exception e)
            {
                Console.WriteLine("I failed: " + e);
                // Couldn't init for some reason (dll errors, blocked ports)
            }
        }
    }
}
```
System:
```
> uname -a
Linux ip-0-0-0-0 4.4.0-1111-aws #123-Ubuntu SMP Sat Jul 4 02:03:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

> dotnet --version
3.1.401
```

At the moment, the error I'm encountering is:
```
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
dlopen failed trying to load:
/home/<user>/.steam/sdk64/steamclient.so
with error:
/home/<user>/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
```
with my bin directory looking as follow when I run `dotnet run` in the root of the project (I copied in `libsteam_api64.so`):
```
total 1064
drwxrwxr-x 2 ubuntu ubuntu   4096 Aug 11 16:57 .
drwxrwxr-x 3 ubuntu ubuntu   4096 Aug 11 16:53 ..
-rwxrw-r-- 1 ubuntu ubuntu 546304 Feb 28 20:07 Facepunch.Steamworks.Win64.dll
-rw-rw-r-- 1 ubuntu ubuntu 403896 Aug 11 16:56 libsteam_api64.so
-rwxr-xr-x 1 ubuntu ubuntu  90552 Aug 11 16:53 steamworksdemo
-rw-rw-r-- 1 ubuntu ubuntu   1039 Aug 11 16:53 steamworksdemo.deps.json
-rw-rw-r-- 1 ubuntu ubuntu   5120 Aug 11 16:53 steamworksdemo.dll
-rw-rw-r-- 1 ubuntu ubuntu   9528 Aug 11 16:53 steamworksdemo.pdb
-rw-rw-r-- 1 ubuntu ubuntu    153 Aug 11 16:53 steamworksdemo.runtimeconfig.dev.json
-rw-rw-r-- 1 ubuntu ubuntu    146 Aug 11 16:53 steamworksdemo.runtimeconfig.json
```

Is there any way this will work? Its hard to tell whether it is compatible and how to proceed with fixing the issue.

**Comment by fanmanpro** [comment]
I've managed to install steamcmd, but now encountering a different error:
```
System.DllNotFoundException: Unable to load shared library 'steam_api64' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libsteam_api64: cannot open shared object file: No such file or directory
   at Steamworks.SteamInternal.Native.SteamInternal_GameServer_Init(UInt32 unIP, UInt16 usPort, UInt16 usGamePort, UInt16 usQueryPort, Int32 eServerMode, String pchVersionString)
   at Steamworks.SteamInternal.GameServer_Init(UInt32 unIP, UInt16 usPort, UInt16 usGamePort, UInt16 usQueryPort, Int32 eServerMode, String pchVersionString)
   at Steamworks.SteamServer.Init(AppId appid, SteamServerInit init, Boolean asyncCallbacks)
   at steamworksdemo.Program.Main(String[] args) in /home/ubuntu/steamworksdemo/Program.cs:line 19
```

Anyone know how I can resolve this? Its only when I run, everything builds just fine.

**Comment by LukekTadej** [comment]
Has this issue been resolved?

**Comment by fanmanpro** [comment]
@LukekTadej nope, I ended up making my own implementation that uses the [Steamworks Web API](https://partner.steamgames.com/doc/webapi).

**Comment by LukekTadej** [comment]
@fanmanpro I managed to fix the same problem you had by setting the Solution Platform and updating all the DLLs, but glad you managed to find a way around it!
