### ISSUE TITLE
Steamworks.SteamClient.Init (System.UInt32 appid, System.Boolean asyncCallbacks) on mac causes error.

### ISSUE THREAD

**Issue by Justusvh** [Facepunch/Facepunch.Steamworks#628]
**Describe the bug**

On Windows, everything works as intended.
On Mac when we Call SteamClient.Init(##App ID##) we get the following error:

```
System.EntryPointNotFoundException: SteamAPI_SteamInput_v006
  at (wrapper managed-to-native) Steamworks.ISteamInput.SteamAPI_SteamInput_v006()
  at Steamworks.ISteamInput.GetUserInterfacePointer () [0x00000] in <655b08adf03f417d87b7d30164d43526>:0 
  at Steamworks.SteamInterface.SetupInterface (System.Boolean gameServer) [0x00061] in <655b08adf03f417d87b7d30164d43526>:0 
  at Steamworks.ISteamInput..ctor (System.Boolean IsGameServer) [0x00006] in <655b08adf03f417d87b7d30164d43526>:0 
  at Steamworks.SteamInput.InitializeInterface (System.Boolean server) [0x00000] in <655b08adf03f417d87b7d30164d43526>:0 
  at Steamworks.SteamClient.AddInterface[T] () [0x00006] in <655b08adf03f417d87b7d30164d43526>:0 
  at Steamworks.SteamClient.Init (System.UInt32 appid, System.Boolean asyncCallbacks) [0x00070] in <655b08adf03f417d87b7d30164d43526>:0 
  at SteamNet.SteamManager.Awake () [0x00027] in /Users/admin/game/game/Assets/Scripts/Steam/SteamManager.cs:61 
UnityEngine.Debug:LogError (object)
SteamNet.SteamManager:Awake () (at Assets/Scripts/Steam/SteamManager.cs:66)
```

We've tested both platforms, in standalone and unity editor.

**To Reproduce**
1. Take a Unity project that calls SteamClient.Init(##App ID##)
2. Launch it in Mac Unity

**Calling Code**
```
// The code you're using to call into Steamworks
SteamClient.Init(##App ID##)
```

**Expected behavior**
As on Windows, we expect it to initialise and connect to steam.

**Desktop (please complete the following information):**
 - OS: [OSX]
- Unity: [Unity 2020.3.25f1]

Any help would be great!
Cheers,
PolyDemons

**Comment by hellur** [comment]
I get the almost same exception on Windows 11. 

Unable to find an entry point named 'SteamAPI_SteamInput_v001' in DLL 'steam_api64'.
`   at Steamworks.ISteamInput.SteamAPI_SteamInput_v001()
   at Steamworks.ISteamInput.GetUserInterfacePointer() in D:\a\Facepunch.Steamworks\Facepunch.Steamworks\Facepunch.Steamworks\Generated\Interfaces\ISteamInput.cs:line 20
   at Steamworks.SteamInterface.SetupInterface(Boolean gameServer) in D:\a\Facepunch.Steamworks\Facepunch.Steamworks\Facepunch.Steamworks\Utility\SteamInterface.cs:line 45
   at Steamworks.ISteamInput..ctor(Boolean IsGameServer) in D:\a\Facepunch.Steamworks\Facepunch.Steamworks\Facepunch.Steamworks\Generated\Interfaces\ISteamInput.cs:line 15
   at Steamworks.SteamInput.InitializeInterface(Boolean server) in D:\a\Facepunch.Steamworks\Facepunch.Steamworks\Facepunch.Steamworks\SteamInput.cs:line 12
   at Steamworks.SteamClient.AddInterface[T]() in D:\a\Facepunch.Steamworks\Facepunch.Steamworks\Facepunch.Steamworks\SteamClient.cs:line 76
   at Steamworks.SteamClient.Init(UInt32 appid, Boolean asyncCallbacks) in D:\a\Facepunch.Steamworks\Facepunch.Steamworks\Facepunch.Steamworks\SteamClient.cs:line 44`

**Comment by hellur** [comment]
Hello again, I just fixed it by rebuilding the sourcecode on my own computer, instead of downloading it.
Using .Net6.0 and Win64.

**Comment by Justusvh** [comment]
> Hello again, I just fixed it by rebuilding the sourcecode on my own computer, instead of downloading it. Using .Net6.0 and Win64.

Did you have to change anything on your SteamClient.Init() for it to connect to steam?
